### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Hands-On-Natural-Language-Processing-with-PyTorch-1.x#1]
Hi there, I was reading this book on packtpub website and the link to the github page of chapter 5 is not working kinldy update the link on the e-book.

**Comment by packt-pradeeps** [comment]
Hi @introvertedbot 

Thanks for pointing this out. I have uploaded an erratum regarding this at [https://github.com/PacktPublishing/Hands-On-Natural-Language-Processing-with-PyTorch-1.x/blob/master/README.md#errata](https://github.com/PacktPublishing/Hands-On-Natural-Language-Processing-with-PyTorch-1.x/blob/master/README.md#errata)
